### ISSUE TITLE
Block or cancel keyboard keys

### ISSUE THREAD

**Issue by HossamMohsen7** [kristian/system-hook#15]
Hello,
Can you implement something like if a specific key is press then cancel the key press or is that already in the project because I want something like that in my application

**Comment by kristian** [comment]
Hello Hossam, blocking keys is not really possible (at least for the current low-level library used for Windows). To explain it in detail, it’s important to understand how low-level hooks work in Windows, my comment in issue #7 explains the details. So the order of hooks determines “who” will get the information. If you are luckly, you’ll be the first one in the chain, so by not calling CallNextHookEx you’ll “block” the key for other programs. But because the behaviour of not calling CallNextHookEx is undefined, the Java library doesn’t implement it. You could go ahead and recompile the C-Library, removing the call to CallNextHookEx. So whenever a keyboard hook is active, the key input won’t be forwarded. Hope this helps. Regards, Kristian
