### ISSUE TITLE
Getting raw input of unregistered keys and mouse buttons

### ISSUE THREAD

**Issue by TrevorCow** [kristian/system-hook#23]
Will there be the future ability to get raw keyboard presses (such as macro keys) as well as mouse buttons (mouse button 4, 5 etc.)?

**Comment by kristian** [comment]
Hi Trevor. I don't own a keyboard with macro keys, so I am a little unsure how keyboards / os handle these. In case (what I assume) they are using specific drivers to capture the macro key presses, I don't think it is feasible to capture these in a library, as it would require propriatory code to work. This library generally uses two different concepts on capturing key presses. You may want to enable "raw" mode (by supplying `true` to the constructor) in order to get the raw keyboard / mouse inputs. Maybe if you are lucky and the inputs of your macro keys will reach the library. Hope this helps.

**Comment by kristian** [comment]
I will close this issue for now, as I havn't heared back from you. In case more input is needed, please feel free to reopen this issue anytime.
