### ISSUE TITLE
Deploy it in a maven-repository or somewhere else, besides github

### ISSUE THREAD

**Issue by balrok** [kristian/system-hook#46]
Hello,
it would be really great if you can deploy the jar on another place besides github.
I have two reasons:
* raw.githubusercontent has not such a high uptime - maybe down once or twice a month (actually it is down  right now, thats why I've looked into your repo ;-))
* I am using nexus to mirror all maven-repositories so I don't need to download so much all the time. But I cannot configure it to mirror this raw.githubusercontent

Thank you in advance

**Comment by kristian** [comment]
Releasing to Maven Central is quite some hastle as it turned out... you need to apply for a repo., to afterwards sign and upload there... However I agree to you, that the GitHub Repo. is no longer state-of-the-art (or never was ;) ). I prepared the first release to Maven Central w/ ecac4d1bdfb38e54940ee748fbd22ffc38da3b89. Let me notify you, as soon as it is available!

**Comment by kristian** [comment]
The library is now available on Maven Central! Enjoy! :)

**Comment by balrok** [comment]
You are the best! :-) thank you very much
